# Site settings
title: Nick Nothom
email: nicknothom@gmail.com
url: https://nicknothom.github.io/
description: "The work and life of Nick Nothom"
skills: "Designer - Engineer - Maker"
meta_author: Nothom Nick

# Description
about1: "My current passion lies in using applied science to create software and machines that enable others to achieve their goals. I like things that swim, drive, and fly."
about2: "I am interested in devices that excite people and in building technologies that make lives better through sensors and algorithms. I make stuff."


# Color Settings (hex-codes without the leading hash)
# I recommend using a site like this: https://www.canva.com/color-palette/
# It will help choose a starting pallete. But you'll need to do some tweaking.

#primary
#Background behind profile pic, and about section
#Choose this color somewhat conservatively. I recommend a darker color. Default: 1F2F42
  
#secondary
#Header, Footer, and large text labels
#This is your accent color, this can pop a little bit. Default: 1F67B4
  
#secondary-dark
#Section marker and copyright tag
#This color should be conservative, but compliment the accent color. Default: 233140
  
#background
#Background behind portfolio and contact forms. Default: 111111
  
color:
  primary: 1F2F42
  secondary: 1F67B4
  secondary-dark: 233140
  background: 111111
  text: ffffff

# Footer settings
footer:
  copyright: Nick Nothom
  location: Saint Paul, Minnesota
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/nick.nothom
  - title: github
    url: https://github.com/NickNothom
  - title: linkedin
    url: https://www.linkedin.com/in/nicholasnothom/


# Relative Path Links
profile_picture: img/profile.png
#baseurl: /instafolio

credits: "Instafolio is developed by me, and utilizes Github Pages, Jekyll, and the Freelancer theme."

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Build settings
markdown: kramdown
permalink: pretty
